TASK 1

In [28]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score


'2.14.0'

In [3]:
# Part 1 - Data Preprocessing
# Importing the dataset
dataset = pd.read_csv("D:\\Churn_Modelling.csv")

In [11]:
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France       0   42   
1             2    15647311       Hill          608     Spain       0   41   
2             3    15619304       Onio          502    France       0   42   
3             4    15701354       Boni          699    France       0   39   
4             5    15737888   Mitchell          850     Spain       0   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France       1   39   
9996       9997    15569892  Johnstone          516    France       1   35   
9997       9998    15584532        Liu          709    France       0   36   
9998       9999    15682355  Sabbatini          772   Germany       1   42   
9999      10000    15628319     Walker          792    France       0   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [10]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France       0   42   
1          2    15647311      Hill          608     Spain       0   41   
2          3    15619304      Onio          502    France       0   42   
3          4    15701354      Boni          699    France       0   39   
4          5    15737888  Mitchell          850     Spain       0   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [30]:
# Part 1 - Data Preprocessing
data = pd.read_csv("D:\\Churn_Modelling.csv")
print(data)
data = data.drop(["RowNumber", "CustomerId", "Surname"], axis=1)

label_encoder = LabelEncoder()
data['Gender'] = label_encoder.fit_transform(data['Gender'])

data = pd.get_dummies(data, columns=["Geography"], drop_first=True)

X_train, X_test, y_train, y_test = train_test_split(data.drop('Exited', axis=1), data['Exited'], test_size=0.2, random_state=42)

      RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMemb

In [5]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [6]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [7]:
# Part 2 - Building the ANN
# Initializing the ANN and setting its parameters
input_layer_size = X_train.shape[1]
hidden_layer_size = 6
output_layer_size = 1
learning_rate = 0.01
epochs = 100

# Initializing and Adding the input layer and the first hidden layer
weights_input_hidden = np.random.normal(scale=1/input_layer_size**0.5, size=(input_layer_size, hidden_layer_size))
bias_hidden = np.zeros((1, hidden_layer_size))

In [12]:
# Adding the second hidden layer if necessary
weights_hidden_hidden = np.random.normal(scale=1/hidden_layer_size**0.5, size=(hidden_layer_size, hidden_layer_size))
bias_hidden2 = np.zeros((1, hidden_layer_size))

# Adding the output layer
weights_hidden_output = np.random.normal(scale=1/hidden_layer_size**0.5, size=(hidden_layer_size, output_layer_size))
bias_output = np.zeros((1, output_layer_size))

In [34]:
# Part 2 - Building the ANN
input_size = X_train.shape[1]
output_size = 1
hidden_layer1_size = 12
hidden_layer2_size = 0

def InitializePara(input_size, HL1S, HL2S, outpu_size):
  np.random.seed(0)
  W1 = np.random.rand(input_size, HL1S)
  B1 = np.zeros((1, HL1S))

  W2 = np.random.rand(HL1S, HL2S) if HL2S else None
  B2 = np.zeros((1, HL2S)) if HL2S else None

  W3 = np.random.rand(HL2S, output_size) if HL2S else np.random.rand(HL1S, output_size)
  B3 = np.zeros((1, output_size))

  return W1, B1, W2, B2, W3, B3

def forwardProp(X, W1, B1):
  X = np.array(X, dtype=float)
  L1_out = np.dot(X, W1) + B1
  L1_act = sigmoid(L1_out)

  return L1_out, L1_act


def addHiddenLayer(X, W, B):
  L_out = np.dot(X, W) + B
  L_act = sigmoid(L_out)

  return L_out, L_act

def outputLayer(X, W, B):
  output = np.dot(X, W) + B
  output_act = sigmoid(output)

  return output, output_act

def sigmoid(x):
  return 1/ (1 + np.exp(-x))

W1, B1, W2, B2, W3, B3 = InitializePara(input_size, hidden_layer1_size, hidden_layer2_size, output_size)
L1_out, L1_act = forwardProp(X_train, W1, B1)

if(hidden_layer2_size):
  L2_out, L2_act = addHiddenLayer(L1_act, W2, B2)

output, output_act = outputLayer(L2_act if hidden_layer2_size else L1_act, W3, B3)

In [36]:


print(L1_out, L1_act)
print(output, output_act)

[[105426.88959237   4117.94167435 148883.96851634 ... 103473.27507576
  106578.47775539 102872.41587192]
 [153034.04524475  47933.72345403 231058.11850607 ... 143486.15928838
  172315.59341324 141752.59383894]
 [ 86882.31122397  43878.3450679  136968.47953213 ...  78780.99953616
  104801.32554279  77509.90789512]
 ...
 [ 54497.25293821   2405.24950828  76896.33787902 ...  53437.68583794
   55183.94795817  53186.88060761]
 [117570.6029463   71659.54523021 189712.62014314 ... 104649.86109543
  146966.03215493 102677.92332921]
 [ 78472.79362843  55408.5522169  129184.34370638 ...  68635.1299131
  101250.12106627  67218.05718508]] [[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]
[[6.49753858]
 [6.49753858]
 [6.49753858]
 ...
 [6.49753858]
 [6.49753858]
 [6.49753858]] [[0.99849512]
 [0.99849512]
 [0.99849512]
 ...
 [0.99849512]
 [0.99849512]
 [0.99849512]]


In [35]:
# Part 3 - Training the ANN
X_train = X_train.astype('float32')
y_train = y_train.astype('int32')
classifier = Sequential()

classifier.add(Dense(units = hidden_layer1_size, kernel_initializer = 'uniform', activation = 'relu', input_dim = input_size))

if(hidden_layer2_size):
    classifier.add(Dense(units = hidden_layer2_size, kernel_initializer = 'uniform', activation = 'relu'))

classifier.add(Dense(units = output_size, kernel_initializer = 'uniform', activation = 'sigmoid'))

classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)


Epoch 1/100
800/800 [==============================] - 2s 2ms/step - loss: 3.6449 - accuracy: 0.6856
Epoch 2/100
800/800 [==============================] - 1s 1ms/step - loss: 2.1171 - accuracy: 0.6869
Epoch 3/100
800/800 [==============================] - 1s 1ms/step - loss: 1.4510 - accuracy: 0.7021
Epoch 4/100
800/800 [==============================] - 1s 1ms/step - loss: 1.0142 - accuracy: 0.7120
Epoch 5/100
800/800 [==============================] - 1s 1ms/step - loss: 0.8561 - accuracy: 0.7241
Epoch 6/100
800/800 [==============================] - 1s 1ms/step - loss: 0.6638 - accuracy: 0.7534
Epoch 7/100
800/800 [==============================] - 1s 1ms/step - loss: 0.6106 - accuracy: 0.7665
Epoch 8/100
800/800 [==============================] - 1s 2ms/step - loss: 0.5472 - accuracy: 0.7840
Epoch 9/100
800/800 [==============================] - 1s 1ms/step - loss: 0.5254 - accuracy: 0.7910
Epoch 10/100
800/800 [==============================] - 1s 1ms/step - loss: 0.5104 - accura

In [37]:
# Part 4 - Making the predictions and evaluating the model

X_test = X_test.astype('float32')
y_test = y_test.astype('int32')

y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

conf_mat = confusion_matrix(y_test, y_pred)

accuracy = accuracy_score(y_test, y_pred)

print("Confusion Matrix:")
print(conf_mat)
print("Accuracy: ", accuracy)


63/63 [==============================] - 0s 1ms/step
Confusion Matrix:
[[1607    0]
 [ 393    0]]
Accuracy:  0.8035


In [22]:
pip install tensorflow

     -------------------------------------- 284.1/284.1 MB 1.3 MB/s eta 0:00:00
     -------------------------------------- 440.7/440.7 kB 1.1 MB/s eta 0:00:00
     -------------------------------------- 938.6/938.6 kB 1.7 MB/s eta 0:00:00
     ---------------------------------------- 24.4/24.4 MB 2.3 MB/s eta 0:00:00
     ---------------------------------------- 57.5/57.5 kB 3.0 MB/s eta 0:00:00
     ---------------------------------------- 65.5/65.5 kB 1.8 MB/s eta 0:00:00
     ---------------------------------------- 1.7/1.7 MB 2.4 MB/s eta 0:00:00
     ---------------------------------------- 1.5/1.5 MB 2.1 MB/s eta 0:00:00
     ---------------------------------------- 5.5/5.5 MB 2.4 MB/s eta 0:00:00
     -------------------------------------- 183.3/183.3 kB 2.7 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [23]:
import tensorflow as tf

Task 2

In [27]:

import numpy as np
from keras.preprocessing import image
import numpy as np
from keras.preprocessing.image import ImageDataGenerator

# Preprocessing the Training set
train_datagen = ImageDataGenerator(rescale = 1./255,
                                   shear_range = 0.2,
                                   zoom_range = 0.2,
                                   horizontal_flip = True)
training_set = train_datagen.flow_from_directory('C:\\Users\\Lenovo\\OneDrive\\Documents\\dataset\\training_set',
                                                 target_size = (64, 64),
                                                 batch_size = 32,
                                                 class_mode = 'binary')

# Preprocessing the Test set
test_datagen = ImageDataGenerator(rescale = 1./255)
test_set = test_datagen.flow_from_directory('C:\\Users\\Lenovo\\OneDrive\\Documents\\dataset\\test_set',
                                            target_size = (64, 64),
                                            batch_size = 32,
                                            class_mode = 'binary')

# Part 2 - Building the CNN

from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Flatten, Dense

cnn = Sequential()

# Step 1 - Convolution
cnn.add(Conv2D(32, (3, 3), input_shape = (64, 64, 3), activation = 'relu'))

# Step 2 - Pooling
cnn.add(MaxPooling2D(pool_size = (2, 2)))

# Adding a second convolutional layer
cnn.add(Conv2D(32, (3, 3), activation = 'relu'))
cnn.add(MaxPooling2D(pool_size = (2, 2)))

# Step 3 - Flattening
cnn.add(Flatten())

# Step 4 - Full Connection
cnn.add(Dense(units = 128, activation = 'relu'))

# Step 5 - Output Layer
cnn.add(Dense(units = 1, activation = 'sigmoid'))

# Part 3 - Training the CNN
cnn.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Training the CNN on the Training set and evaluating it on the Test set
cnn.fit(x = training_set, validation_data = test_set, epochs = 25)


# Part 4 - Making a single prediction
test_image = image.load_img('C:\\Users\\Lenovo\\OneDrive\\Documents\\dataset\\single_prediction\\cat_or_dog_1.jpg', target_size = (64, 64))
test_image = image.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis = 0)
result = cnn.predict(test_image)
training_set.class_indices
if result[0][0] == 1:
    prediction = 'dog'
else:
    prediction = 'cat'
print(prediction)

Found 8000 images belonging to 2 classes.
Found 2000 images belonging to 2 classes.
Epoch 1/25
250/250 [==============================] - 123s 488ms/step - loss: 0.6729 - accuracy: 0.5838 - val_loss: 0.6344 - val_accuracy: 0.6395
Epoch 2/25
250/250 [==============================] - 46s 184ms/step - loss: 0.6119 - accuracy: 0.6671 - val_loss: 0.5851 - val_accuracy: 0.6945
Epoch 3/25
250/250 [==============================] - 47s 188ms/step - loss: 0.5518 - accuracy: 0.7210 - val_loss: 0.5182 - val_accuracy: 0.7490
Epoch 4/25
250/250 [==============================] - 47s 188ms/step - loss: 0.5184 - accuracy: 0.7444 - val_loss: 0.5267 - val_accuracy: 0.7405
Epoch 5/25
250/250 [==============================] - 47s 187ms/step - loss: 0.4987 - accuracy: 0.7550 - val_loss: 0.5015 - val_accuracy: 0.7615
Epoch 6/25
250/250 [==============================] - 47s 187ms/step - loss: 0.4848 - accuracy: 0.7640 - val_loss: 0.4796 - val_accuracy: 0.7675
Epoch 7/25
250/250 [=========================